lkl tools: use 64-bit lkl_sys_nanosleep on 32-bit builds
Use the always-64-bit __lkl__kernel_timespec struct for
lkl_sys_nanosleep calls and rewrite the lkl_sys_nanosleep_time32 wrapper
to use __lkl__NR_clock_nanosleep_time64 on 32-bit builds.

This fixes the following -Wincompatible-pointer-types errors:

 lib/fs.c:287:43: error: passing argument 1 of ‘lkl_sys_nanosleep_time32’ from incompatible pointer type [-Wincompatible-pointer-types]
   287 |                         lkl_sys_nanosleep((struct __lkl__kernel_timespec *)&ts,
       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |                                           |
       |                                           struct __lkl__kernel_timespec *
 In file included from tools/lkl//include/lkl_host.h:9,
                  from lib/fs.c:5:
 tools/lkl//include/lkl.h:68:65: note: expected ‘struct lkl_timespec *’ but argument is of type ‘struct __lkl__kernel_timespec *’
    68 | static inline int lkl_sys_nanosleep_time32(struct lkl_timespec *rqtp,
       |                                            ~~~~~~~~~~~~~~~~~~~~~^~~~
 make[1]: *** [tools/build/Makefile.build:98: tools/lkl/lib/fs.o] Error 1

Signed-off-by: David Disseldorp <ddiss@suse.de>
(cherry picked from commit ef3fb8c37b7c397d4f874b7afceda7e48fd9a461)