lkl: silence bootmem compiler warning
gcc-14 complains about the type mismatch:
arch/lkl/mm/bootmem.c: In function ‘bootmem_init’:
arch/lkl/mm/bootmem.c:39:35: error: passing argument 1 of ‘virt_to_pfn’
makes pointer from integer without a cast [-Wint-conversion]
   39 |         max_low_pfn = virt_to_pfn(memory_end);
      |                                   ^~~~~~~~~~
      |                                   |
      |                                   long unsigned int
...
./include/asm-generic/page.h:77:53: note: expected ‘const void *’ but
argument is of type ‘long unsigned int’
   77 | static inline unsigned long virt_to_pfn(const void *kaddr)
      |                                         ~~~~~~~~~~~~^~~~~

Add a cast to silence the warning. Drop some unnecessary casts for
_memory_start and empty_zero_page, which can both be void *.

Signed-off-by: David Disseldorp <ddiss@suse.de>
(cherry picked from commit b1339686dbc0866caf49c0fd57b70fbceb543680)