lkl: hijack: explicitly build with -std=gnu11
HOST_CALL() uses a (*host_##name)() function pointer while callers
provide regular syscall parameters. With gcc -std=gnu23 this results in:
lib/hijack/hijack.c: In function ‘hijack_setsockopt’:
lib/hijack/hijack.c:176:24: error: too many arguments to function ‘host_setsockopt’; expected 0, have 5
  176 |                 return host_setsockopt(fd, level, optname, optval, optlen);
      |                        ^~~~~~~~~~~~~~~ ~~

Signed-off-by: David Disseldorp <ddiss@suse.de>
(cherry picked from commit bd30a15647247495b9b472b2a05c23e007e1a32a)